version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - pgsqldb
    environment:
      - DB_HOST=pgsqldb
      - DB_NAME=cms_db_postgres
  migration:
    build:
      context: ./backend
    links:
      - pgsqldb
    depends_on:
      - pgsqldb
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "pgsqldb:5432",
        "--",
        "yarn",
        "migration:run",
      ]
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=pgsqldb
      - DB_NAME=cms_db_postgres

  pgsqldb:
    image: postgres:latest
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "cms_db_postgres"
    ports:
      - 5432:5432
    volumes:
      - pgsqldata:/data/postgresql/data

volumes:
  pgsqldata:
