version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - pgsqldb
    environment:
      - DB_HOST=pgsqldb
      - DB_NAME=cms_db_postgres
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
  pgsqldb:
    image: postgres:latest
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "cms_db_postgres"
    ports:
      - 5432:5432
    volumes:
      - pgsqldata:/data/postgresql/data

  chrome:
    platform: linux/amd64
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
  selenium-hub:
    platform: linux/amd64
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

volumes:
  pgsqldata:
